services:
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./private-registry/data:/var/lib/registry
      - ./private-registry/auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  api:
    build: ./registry-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./private-registry/auth:/usr/src/app/auth:rw
    depends_on:
      - registry
    environment:
      - REGISTRY_API=http://registry:5000/v2
      - AUDIT_FILE=./data/audit.log
